### PR TITLE
dinit-service: The new `restart = on-failure` option!

### LINKED ISSUE #271: restart only when exit unexpected
Can Dinit implement a functionality similar to Supervisor's automatic restart on abnormal exit? 
Specifically,
1.when the program exits with a status code not present in the exitcode list, it should be considered an abnormal exit, triggering an automatic restart. 
2.If the program exits normally with a status code within the exitcode list, no automatic restart is needed. 
Currently, Dinit automatically restarts in all situations, which is not very convenient.

### PR DESCRIPTION
**Pull request by mobin-2008**
Commits are self-explanatory. It also has a build-time configuration for setting it.

Fixes #271

`Signed-off-by: Mobin Aydinfar <mobin@mobintestserver.ir>`

### CODE REVIEW

File: BUILD [hunk 1]
```diff
@@ -165,6 +165,10 @@ USE_INITGROUPS=1|0
     by default. If it is not supported on yours, you can explicitly disable it.
 DEFAULT_AUTO_RESTART=true|false
     Enable/disable auto-restart for services by default. The default if unspecified is "true".
+DEFAULT_FAIL_ONLY_AUTO_RESTART=true|false
+    Enable/disable auto-restart on >0 exit codes for services by default.
+    The default if unspecified is "false".
+    This variable and DEFAULT_AUTO_RESTART have conflict with each other and should not enabled together.
```
Comment (nekopsykose) [inline BUILD:171]:
```suggestion
    This variable and DEFAULT_AUTO_RESTART conflict with each other and should not be enabled together.
```

File: BUILD_MESON [hunk 2]
```diff
@@ -140,6 +140,12 @@ Custom options:
                              Available values : true, false
                              Default value : true
 
+ default-fail-only-auto-restart
+                           : Enable/disable auto-restart only on >0 exit code for services by default
+                             Note: This option has conflict with default-auto-restart.
```
Comment (nekopsykose) [inline BUILD_MESON:145]:
```suggestion
                             Note: This option conflicts with default-auto-restart.
```

File: src/includes/service.h [hunk 3]
```diff
@@ -266,7 +266,9 @@ class service_record
     environment service_env; // holds the environment populated during load
     const char *service_dsc_dir = nullptr; // directory containing service description file
 
-    bool auto_restart : 1;    // whether to restart this (process) if it dies unexpectedly
+    // Note: auto_restart and failure_only_auto_restart have conflict with each other!
```
Comment (nekopsykose) [inline src/includes/service.h:269]:
```suggestion
    // Note: auto_restart and failure_only_auto_restart conflict with each other!
```

File: src/includes/service.h [hunk 4]
```diff
@@ -572,7 +574,14 @@ class service_record
     {
         this->auto_restart = auto_restart;
     }
-    
+
+    // Set whether this server should automatically restart only when it dies with >0 exit code
+    // Note: Always use set_auto_restart OR this function! These have conflict with each other.
```
Comment (nekopsykose) [inline src/includes/service.h:579]:
```suggestion
    // Note: Always use set_auto_restart OR this function! These conflict with each other.
```

**Review by nekopsykose — COMMENTED** [review]
just some light grammar

**Comment by mobin-2008** [comment]
@lfxx Can you test my branch? I tested it and everything works as expected, Just to make sure, compile it and run a daemon with `restart = on-failure` option.

**Comment by davmac314** [comment]
@mobin-2008 review was requested but you are still pushing changes. What's the deal?

**Comment by mobin-2008** [comment]
I just added a small comments in configs about those auto-restart conflict, No more change.
Sorry about confusion, Everything is ready for review.

**Comment by mobin-2008** [comment]
> * The change in src/tests/test-includes/baseproc-sys.h doesn't make sense to me,. won't this just always return 0?

https://github.com/davmac314/dinit/blob/213d3fb1bff820f9cbe981193ad06c103d787405/src/includes/proc-service.h#L536-L539

As you see "base_process_service" exit_status is checked through `as_int()` and I guess it represents the exit code of process. I tested by patches with `return 0` and fail-only restart test failed:
```
...
test_proc_term_restart5...    proctests: proctests.cc:492: void test_proc_term_restart5(): Assertion `p.get_target_state() == service_state_t::STARTED' failed.
...
```
So I think we should return `status` in that header.

File: src/proc-service.cc [hunk 5]
```diff
@@ -320,6 +320,8 @@ void process_service::handle_exit_status(bp_sys::exit_status exit_status) noexce
     bool was_signalled = exit_status.was_signalled();
     auto current_state = get_state();
 
+    this->exit_status = exit_status;
```
Comment (davmac314) [inline src/proc-service.cc:323]: This should not be necessary

Comment (mobin-2008) [reply src/proc-service.cc:323]: test fails without this but I'm going to check `restart = on-failure` in production environment.

Comment (mobin-2008) [reply src/proc-service.cc:323]: I designed a little test for this new feature as below:
(turnstile runs my branch of dinit)
script service:
```
type = process
command = /tmp/script.sh
restart = on-failure
restart-limit-count = 12
log-type = buffer
```
script source:
```
#!/bin/sh

if ! grep "1" /tmp/script.mem; then
    echo "1" >> /tmp/script.mem
    exit 1
fi

if ! grep "2" /tmp/script.mem; then
    echo "2" >> /tmp/script.mem
    exit 2
fi

exit 0
```
run:
```
[mobin@Mobin-Mehdi-PC ~]$ echo "" > /tmp/script.mem
[mobin@Mobin-Mehdi-PC ~]$ dinitctl start script
Service 'script' started.
[mobin@Mobin-Mehdi-PC ~]$ dinitctl catlog script
1
(dinit: note: service restarted)
1
2
[mobin@Mobin-Mehdi-PC ~]$ echo "" > /tmp/script.mem
[mobin@Mobin-Mehdi-PC ~]$ nano ~/.config/dinit.d/script # Changing restart to true
[mobin@Mobin-Mehdi-PC ~]$ dinitctl reload script
Service 'script' reloaded.
[mobin@Mobin-Mehdi-PC ~]$ dinitctl start script
Service 'script' started.
[mobin@Mobin-Mehdi-PC ~]$ dinitctl catlog script
1
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
(dinit: note: service restarted)
1
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
(dinit: note: service restarted)
1
2
```

Looks like it does work in production environment but not in test environment. @davmac314 Do I should skip test for now? I think exit_status handling needs major refactor.

Comment (davmac314) [reply src/proc-service.cc]: > Do I should skip test for now?

As I said already, we can skip the test for now.

> I think exit_status handling needs major refactor.

I think you are jumping to conclusions here, it needs a small rework in my assessment.

File: src/includes/load-service.h [hunk 6]
```diff
@@ -974,7 +974,7 @@ class service_settings_wrapper
     unsigned max_log_buffer_sz = 4096;
     service_flags_t onstart_flags;
     int term_signal = SIGTERM;  // termination signal
-    bool auto_restart = DEFAULT_AUTO_RESTART;
+    int auto_restart = auto_restart_mode::DEFAULT_AUTO_RESTART;
```
Comment (davmac314) [inline src/includes/load-service.h:977]: Should be enum type,not `int`

File: src/proc-service.cc (hunk 5 above)
Comment (mobin-2008) [reply src/proc-service.cc]: test is commented out and I yeah, It's already decent

File: src/includes/service-constants.h [hunk 7]
```diff
@@ -125,6 +125,13 @@ enum class log_type_id
     PIPE      // pipe to another process (service)
 };
 
+enum auto_restart_mode
```
Comment (davmac314) [inline src/includes/service-constants.h:128]: prefer `enum class`

File: src/includes/service.h [hunk 8]
```diff
@@ -266,7 +266,8 @@ class service_record
     environment service_env; // holds the environment populated during load
     const char *service_dsc_dir = nullptr; // directory containing service description file
 
-    bool auto_restart : 1;    // whether to restart this (process) if it dies unexpectedly
+    int auto_restart : 2; // whether to restart this (process) if it dies unexpectedly
```
Comment (davmac314) [inline src/includes/service.h:269]: should be enum type

File: src/includes/service.h [hunk 9]
```diff
@@ -266,7 +266,8 @@ class service_record
...
+                          // Possible values are: auto_restart_mode::{NEVER, ALWAYS, ON_FAIL}
```
Comment (davmac314) [inline src/includes/service.h:270]: ... and then you don't need to document the possible values here, they are part of the type.

File: BUILD [hunk 10]
```diff
@@ -163,8 +163,9 @@ USE_INITGROUPS=1|0
     Whether to initialize supplementary groups for run-as services. The C API for this is not
     in POSIX, but is in practice supported on just about every relevant system, so it is enabled
     by default. If it is not supported on yours, you can explicitly disable it.
-DEFAULT_AUTO_RESTART=true|false
-    Enable/disable auto-restart for services by default. The default if unspecified is "true".
+DEFAULT_AUTO_RESTART=ALWAYS|FAIL_ONLY|NEVER
```
Comment (davmac314) [inline BUILD:166]: Change `FAIL_ONLY` to `ON_FAILURE`

File: doc/manpages/dinit-service.5.m4 [hunk 11]
```diff
@@ -182,13 +182,16 @@ Variable substitution is not performed on the \fBenv\-file\fR property value its
 If the path is not absolute, it is resolved relative to the directory containing the service
 description.
 .TP
-\fBrestart\fR = {yes | true | no | false}
+\fBrestart\fR = {yes | true | on-failure | no | false}
 Indicates whether the service should automatically restart if it stops, including due to
-unexpected process termination or a dependency stopping.
+unexpected process termination or a dependency stopping. "on-failure" is special option
+and indicates auto-restart should happen only when exit code of process is not equal to 0.
```
Comment (davmac314) [inline doc/manpages/dinit-service.5.m4:188]: ... "when _the_ exit code of _the service_ process is not equal to 0".

Use semicolon not full stop between "dependency stopping" and ""on-failure"".

What if it's not a process-based service?

File: doc/manpages/dinit-service.5.m4 [hunk 12]
```diff
@@ -182,13 +182,16 @@ Variable substitution is not performed on the \fBenv\-file\fR property value its
...
 Note that if a service stops due to user request, automatic restart is inhibited.
 $$$changequote(`,')dnl
-ifelse(DEFAULT_AUTO_RESTART, true,
+ifelse(DEFAULT_AUTO_RESTART, ALWAYS,
     ``The default is to automatically restart.'',
+    DEFAULT_AUTO_RESTART, FAIL_ONLY,
+    ``the default is to automatically restart only on non-zero exit code.'',
```
Comment (davmac314) [inline doc/manpages/dinit-service.5.m4:194]: What if the process terminates due to a signal?

File: meson_options.txt [hunk 13]
```diff
@@ -60,9 +60,10 @@ option(
 )
 option(
     'default-auto-restart',
-    type : 'boolean',
-    value : true,
-    description : 'Enable/disable auto-restart for services by default.'
+    type : 'combo',
+    choices : ['ALWAYS', 'FAIL_ONLY', 'NEVER'],
+    value : 'ALWAYS',
+    description : 'Always/never/"only on non-zero exit" auto-restart for services by default.'
```
Comment (davmac314) [inline meson_options.txt:66]: What if the process terminates due to a signal?

File: src/includes/service.h [hunk 14]
```diff
@@ -458,7 +459,7 @@ class service_record
     // any appropriate cleanup.
     virtual void becoming_inactive() noexcept { }
 
-    // Check whether the service should automatically restart (assuming auto_restart is true)
+    // Check whether the service should automatically restart (assuming auto_restart is ALWAYS)
```
Comment (davmac314) [inline src/includes/service.h:462]: The comment implies that this function isn't used if auto_restart is ON_FAIL, but that can't be right?

File: src/tests/proctests.cc [hunk 15]
```diff
@@ -458,6 +458,64 @@ void test_proc_term_restart4()
     sset.remove_service(&p);
 }
 
+// ToDo: There is some problems around exit_status handling in test environment
```
Comment (davmac314) [inline src/tests/proctests.cc:461]: Change ToDo to TODO, stick with the same convention already used elsewhere.
Grammar: There _are_ some problems ...

**Review by davmac314 — COMMENTED** [review]
You didn't really address all my previous review:

> What about if the service isn't a process-based service? This needs complete and accurate documentation.

Please take the time to address everything, and don't rush. Also make sure you follow existing conventions (eg use "TODO" not "ToDo", this is important as it allows easily finding all TODO items in the code).

File: doc/manpages/dinit-service.5.m4 (hunk 11 above)
Comment (davmac314) [reply doc/manpages/dinit-service.5.m4:188]: Also: how does this apply to `scripted` services?

File: src/tests/proctests.cc (hunk 15 above)
Comment (davmac314) [reply src/tests/proctests.cc:461]: (But more accurately: There _is a problem_ ...)

File: doc/manpages/dinit-service.5.m4 (hunk 12 above)
Comment (mobin-2008) [reply doc/manpages/dinit-service.5.m4:194]: Looks like systemd doesn't restart on SIGHUP, SIGINT, SIGTERM and SIGPIPE signals (Ref: https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Restart=).

I think it's reasonable to treat some signals as clean exit status in addition of 0 exit code. I think it could be configurable in build-time with default of SIGHUP, SIGINT, SIGTERM.

Comment (davmac314) [reply doc/manpages/dinit-service.5.m4:194]: Treating those signals as special cases is fine if you want to implement that, my point was that the behaviour implemented in the PR right now is to always restart if the process terminates due to a signal, but the documentation here (or in the man page) doesn't say anything about that. The documentation should be clear and complete.

I don't think we should have a build-time option to specify which set of signals count as a clean exit. Too many build-time options makes testing harder and leads to diverging behaviour in deployments which is bad for the user experience.  Just make a reasonable choice and document it (or leave the behaviour as it is, i.e. restart for termination via _any_ signal, but make sure it is documented properly). 

Also, the documentation needs to be clear that this "auto restart" only applies to process-based services, not including `scripted` services (i.e. only to`process` and `bgprocess` services).

Comment (mobin-2008) [reply doc/manpages/dinit-service.5.m4:194]: I will treat `SIGHUP`, `SIGINT`, `SIGUSR1`, `SIGUSR2` and `SIGTERM` as clean exit status because one of use cases of this is on configuration reload. These signals (specially first four ones) are used for daemon config reloads, If that fail daemons usually refuse to run and restarting that daemon doesn't make any benefit.

File: src/includes/service.h (hunk 14 above)
Comment (mobin-2008) [reply src/includes/service.h]: Yes, It wasn't right. The right thing is `(assuming auto_restart is ALWAYS or ON_FAILURE)`

File: meson_options.txt (hunk 13 above)
Comment (mobin-2008) [reply meson_options.txt]: See our discussion above and `dinit-service(5)` in this PR.

File: doc/manpages/dinit-service.5.m4 (hunk 12 above)
Comment (mobin-2008) [reply doc/manpages/dinit-service.5.m4]: Close this if everything is fixed.

File: doc/manpages/dinit-service.5.m4 [hunk 16]
```diff
@@ -182,13 +182,16 @@ Variable substitution is not performed on the \fBenv\-file\fR property value its
 If the path is not absolute, it is resolved relative to the directory containing the service
 description.
 .TP
-\fBrestart\fR = {yes | true | no | false}
+\fBrestart\fR = {yes | true | on-failure | no | false}
 Indicates whether the service should automatically restart if it stops, including due to
-unexpected process termination or a dependency stopping.
+unexpected process termination or a dependency stopping. "on-failure" is special option
```
[the remark this answers is not in the document]
Comment (mobin-2008) [reply doc/manpages/dinit-service.5.m4]: Documented in that man-page

File: src/includes/proc-service.h [hunk 17]
```diff
@@ -538,6 +538,11 @@ class base_process_service : public service_record
         return exit_status.as_int();
     }
 
+    int get_term_sig() noexcept override
+    {
+        return exit_status.get_term_sig();
+    }
```
Comment (davmac314) [inline src/includes/proc-service.h:544]: This shouldn't be needed, I will explain in other comment.

**Review by davmac314 — CHANGES_REQUESTED** [review]
It's not too bad but it's functionally not sound and I'm concerned it hasn't been tested properly. Please see the comments. With the right changes I think you could get the unit tests working.

File: src/service.cc [hunk 18]
```diff
@@ -652,7 +652,22 @@ void service_record::do_stop(bool with_restart) noexcept
...
 
     // Will we restart? desired state of STOPPED inhibits auto-restart
-    bool for_restart = with_restart || (auto_restart && desired_state == service_state_t::STARTED);
+    bool do_auto_restart = false;
+    if (auto_restart == auto_restart_mode::ALWAYS) {
+        do_auto_restart = true;
+    }
+    else if (auto_restart == auto_restart_mode::ON_FAILURE) {
+        if (get_type() == service_type_t::PROCESS || get_type() == service_type_t::BGPROCESS) {
+            if (get_exit_status() != 0) {
```
[the remark this answers is not in the document]
Comment (davmac314) [reply src/service.cc:661]: > If get_exit_status() returned the actual bp_sys::exit_status

(What I mean by this is that the return type of `get_exit_status()` should be changed to `bp_sys::exit_status`.)

**Comment by mobin-2008** [comment]
I don't understand the logic of setting current `exit_status`. In production code caller should set exit_status of service from POSIX status code. But we also have a function called `handle_exit_status()` which also gets a exit_status in its parameters.

So what did you mean by doing both of them? If `handle_exit_status()` should be responsible for setting current exit_status, Why it doesn't? or if it's not responsible for doing so, it should use current exit_status from service variables, not getting it from its parameters.

https://github.com/davmac314/dinit/blob/15c61b59b74f7eab40718a91ee78e2ada8dc5d12/src/proc-service.cc#L242-L258
According to this, I choose first approach, Caller should set exit_status before calling `handle_exit_status()` and `handle_exit_status()` should use it from service variables.

File: src/service.cc (hunk 18 above)
[the remark this answers is not in the document]
Comment (mobin-2008) [reply src/service.cc]: I fixed tests and also I ran two tests in my computer to make sure everything works.

File: src/includes/service-constants.h [hunk 19]
```diff
@@ -125,6 +125,15 @@ enum class log_type_id
     PIPE      // pipe to another process (service)
 };
 
+enum class auto_restart_mode
+{
+    NEVER,      // Never do auto-restart
+    ALWAYS,     // Always do auto-restart
+    ON_FAILURE, // Only do auto-restart when exit unexpectedly.
+                // unexpected exit means exit_code != 0 or  signalled with any signal
+                // other than SIGHUP, SIGINT, SIGUSR1, SIGUSR2 or SIGTERM.
```
[the remark this answers is not in the document]
Comment (mobin-2008) [reply src/includes/service-constants.h]: Details removed from this comment, Also I replaced unexpected exit with process fails (or process failure) in this comment and docs.

File: src/proc-service.cc (hunk 5 above)
Comment (mobin-2008) [reply src/proc-service.cc]: Tests are fixed.

File: doc/manpages/dinit-service.5.m4 [hunk 20]
```diff
@@ -173,13 +173,19 @@ Variable substitution is not performed on the \fBenv\-file\fR property value its
 If the path is not absolute, it is resolved relative to the directory containing the service
 description.
 .TP
-\fBrestart\fR = {yes | true | no | false}
+\fBrestart\fR = {yes | true | on-failure | no | false}
 Indicates whether the service should automatically restart if it stops, including due to
-unexpected process termination or a dependency stopping.
+unexpected process termination or a dependency stopping; \fBon-failure\fR indicates auto-restart
+should only happen when exit code of process is not equal to 0 or signalled with any other
+signal than SIGHUP, SIGINT, SIGUSR1, SIGUSR2 or SIGTERM. the \fBon-failure\fR only works for
```
Comment (davmac314) [inline doc/manpages/dinit-service.5.m4:180]: Always use new line before beginning a new sentence in the man pages (see the README).

Grammar: letters at the start of a sentence should be capital (it should be "The" not "the").

**Review by davmac314 — CHANGES_REQUESTED** [review]
Please do not rebase in-progress PRs onto master if it is not actually necessary. When it has been rebased I cannot compare it to the previous version of the PR and this makes it much harder to review.

I pushed all suggested wording changes to this branch: https://github.com/davmac314/dinit/tree/pr-338

Please pick commit e5c7f744a3bb6c15efa89b56319df510f004fb5d and squash it in.

Please squash all of these commits into a single commit:
8eba8ac4271d24533b98048026aed0eb66a471ef
a425d88df690a6dce3893d23c03c3dd04f0b47c7
6bf4753a00779444bfabed7eb608bf3892bba7dd
f808e533903cbda14737c1d06d532ec4ba0a3c50

These are not independent changes so they should not be in separate commits. (If they are not all included, build/check fails).

Everything else is ok - just needs the rewording and squash the commits properly.

**Comment by mobin-2008** [comment]
> Please do not rebase in-progress PRs onto master if it is not actually necessary. When it has been rebased I cannot compare it to the previous version of the PR and this makes it much harder to review.

I didn't know that, I will rebase in-progress PRs only if there is conflict.

@davmac314 I squashed commits in `pr-338` branch and it's ready for review.

**Comment by davmac314** [comment]
> I squashed commits in `pr-338` branch and it's ready for review.

You need to push the changes to your own branch for them to show up in the PR.

**Comment by mobin-2008** [comment]
> > I squashed commits in `pr-338` branch and it's ready for review.
> 
> You need to push the changes to your own branch for them to show up in the PR.

Can you merge it manually from that branch?

**Comment by davmac314** [comment]
> Can you merge it manually from that branch?

I would like to look over it beforehand, can you please push the changes to your branch

**Comment by mobin-2008** [comment]
> I would like to look over it beforehand, can you please push the changes to your branch

I think it will be better to open a new PR for that purpose.

**Comment by davmac314** [comment]
@mobin-2008 No, just push the commits to your PR branch please.

**Comment by mobin-2008** [comment]
> @mobin-2008 No, just push the commits to your PR branch please. I don't want to lose the review history either.
> 
> This should be very easy to do.

That's OK, I'm going to do that.

**Review by davmac314 — APPROVED** [review]
Looks good now, thanks
